### PR TITLE
Update blue_noise_particles.py

### PR DESCRIPTION
**Pull request by theoldben**
Updates to the changed API of 2.8 Stable which removed the depsgraph object.

### CODE REVIEW

**Review by dmerziii — APPROVED** [review]
This fixed the problem for me, the addon is working again.

**Comment by theoldben** [comment]
What version are you on, out of curiosity?

**Comment by theoldben** [comment]
Just tested it on today's 2.81 Alpha. Works fine.

**Comment by BorisTheBrave** [comment]
Wow thanks. Now I'm kinda glad I slacked off and didn't get around to fixing this myself. I was on 2.80 (sub 51) beta, i had assumed that was sufficient.

I've upgraded to 2.80.75 and your changes work fine.

**Comment by theoldben** [comment]
Thanks for making the add-on. The distributions you can get with it are fantastic!

**Comment by BorisTheBrave** [comment]
I'm glad you like it. You can always send me some of your compositions to add to the gallery.

**Pull request merged**
